CREATE TABLE USER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PROFILE_IMAGE TEXT NOT NULL,
    CREATED_DATE DATE NOT NULL
);

CREATE TABLE CONTENT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(16) NOT NULL,
    WIDTH INT,
    HEIGHT INT,
    DATA TEXT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    USER_ID BIGINT
);



